second screen all ready
Ivan-Tarasenko/Collections pull request #9
Opened 2022-03-08 12:54 UTC by Ivan-Tarasenko

2022-03-08 20:08 UTC, JJefro requested changes

2022-03-09 11:56 UTC, Ivan-Tarasenko commented on Collections/Support/Custom TextField/Custom View/SetTextFields.swift
> +class CustomView: UIView {
this is a reused TextField from the TextFields project. Let's review it later.

2022-03-09 11:56 UTC, Ivan-Tarasenko commented on Collections/Support/Custom TextField/Custom View/SetTextFields.swift
> +    private let checkEnglishChar = "[а-яА-Я]"
this is a reused TextField from the TextFields project. Let's review it later.

2022-03-09 11:56 UTC, Ivan-Tarasenko commented on Collections/Support/Custom TextField/Custom View/SetTextFields.swift
> +    let customPassValid = CustomPassValid()
this is a reused TextField from the TextFields project. Let's review it later.

2022-03-09 11:56 UTC, Ivan-Tarasenko commented on Collections/Support/Custom TextField/Extension/UILabel+SafeText.swift
> +    var textTitle: String {
this is a reused TextField from the TextFields project. Let's review it later.

2022-03-09 11:56 UTC, Ivan-Tarasenko commented on Collections/Support/Custom TextField/Models/Models.swift
> +    case validationRules
this is a reused TextField from the TextFields project. Let's review it later.

2022-03-09 12:00 UTC, Ivan-Tarasenko commented on Collections/Controllers/ArrayViewController/ArrayViewController.swift
> +class ArrayViewController: UICollectionViewController {
why must to use UIViewController instead of UICollectionViewController?

2022-03-09 12:02 UTC, Ivan-Tarasenko commented on Collections/Controllers/MainViewController/MainViewController.swift
> +        cell.textLabel?.text = name.nameCell
why? won't this worsen the readability of the code?

2022-06-03 09:55 UTC, merged